// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/proc/v1/proc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnProcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binary        string                 `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnProcRequest) Reset() {
	*x = SpawnProcRequest{}
	mi := &file_proto_proc_v1_proc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnProcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnProcRequest) ProtoMessage() {}

func (x *SpawnProcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proc_v1_proc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnProcRequest.ProtoReflect.Descriptor instead.
func (*SpawnProcRequest) Descriptor() ([]byte, []int) {
	return file_proto_proc_v1_proc_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnProcRequest) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *SpawnProcRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SpawnProcRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type SpawnProcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnProcResponse) Reset() {
	*x = SpawnProcResponse{}
	mi := &file_proto_proc_v1_proc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnProcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnProcResponse) ProtoMessage() {}

func (x *SpawnProcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proc_v1_proc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnProcResponse.ProtoReflect.Descriptor instead.
func (*SpawnProcResponse) Descriptor() ([]byte, []int) {
	return file_proto_proc_v1_proc_proto_rawDescGZIP(), []int{1}
}

func (x *SpawnProcResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SpawnProcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SpawnLXCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnLXCRequest) Reset() {
	*x = SpawnLXCRequest{}
	mi := &file_proto_proc_v1_proc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnLXCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnLXCRequest) ProtoMessage() {}

func (x *SpawnLXCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proc_v1_proc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnLXCRequest.ProtoReflect.Descriptor instead.
func (*SpawnLXCRequest) Descriptor() ([]byte, []int) {
	return file_proto_proc_v1_proc_proto_rawDescGZIP(), []int{2}
}

func (x *SpawnLXCRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *SpawnLXCRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SpawnLXCRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type SpawnLXCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnLXCResponse) Reset() {
	*x = SpawnLXCResponse{}
	mi := &file_proto_proc_v1_proc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnLXCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnLXCResponse) ProtoMessage() {}

func (x *SpawnLXCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proc_v1_proc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnLXCResponse.ProtoReflect.Descriptor instead.
func (*SpawnLXCResponse) Descriptor() ([]byte, []int) {
	return file_proto_proc_v1_proc_proto_rawDescGZIP(), []int{3}
}

func (x *SpawnLXCResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SpawnLXCResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_proc_v1_proc_proto protoreflect.FileDescriptor

const file_proto_proc_v1_proc_proto_rawDesc = "" +
	"\n" +
	"\x18proto/proc/v1/proc.proto\x12\aproc.v1\"c\n" +
	"\x10SpawnProcRequest\x12\x16\n" +
	"\x06binary\x18\x01 \x01(\tR\x06binary\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"=\n" +
	"\x11SpawnProcResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"s\n" +
	"\x0fSpawnLXCRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"M\n" +
	"\x10SpawnLXCResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x92\x01\n" +
	"\vProcService\x12B\n" +
	"\tSpawnProc\x12\x19.proc.v1.SpawnProcRequest\x1a\x1a.proc.v1.SpawnProcResponse\x12?\n" +
	"\bSpawnLXC\x12\x18.proc.v1.SpawnLXCRequest\x1a\x19.proc.v1.SpawnLXCResponseB+Z)github.com/j33pguy/33-linux/proto/proc/v1b\x06proto3"

var (
	file_proto_proc_v1_proc_proto_rawDescOnce sync.Once
	file_proto_proc_v1_proc_proto_rawDescData []byte
)

func file_proto_proc_v1_proc_proto_rawDescGZIP() []byte {
	file_proto_proc_v1_proc_proto_rawDescOnce.Do(func() {
		file_proto_proc_v1_proc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proc_v1_proc_proto_rawDesc), len(file_proto_proc_v1_proc_proto_rawDesc)))
	})
	return file_proto_proc_v1_proc_proto_rawDescData
}

var file_proto_proc_v1_proc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_proc_v1_proc_proto_goTypes = []any{
	(*SpawnProcRequest)(nil),  // 0: proc.v1.SpawnProcRequest
	(*SpawnProcResponse)(nil), // 1: proc.v1.SpawnProcResponse
	(*SpawnLXCRequest)(nil),   // 2: proc.v1.SpawnLXCRequest
	(*SpawnLXCResponse)(nil),  // 3: proc.v1.SpawnLXCResponse
}
var file_proto_proc_v1_proc_proto_depIdxs = []int32{
	0, // 0: proc.v1.ProcService.SpawnProc:input_type -> proc.v1.SpawnProcRequest
	2, // 1: proc.v1.ProcService.SpawnLXC:input_type -> proc.v1.SpawnLXCRequest
	1, // 2: proc.v1.ProcService.SpawnProc:output_type -> proc.v1.SpawnProcResponse
	3, // 3: proc.v1.ProcService.SpawnLXC:output_type -> proc.v1.SpawnLXCResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proc_v1_proc_proto_init() }
func file_proto_proc_v1_proc_proto_init() {
	if File_proto_proc_v1_proc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proc_v1_proc_proto_rawDesc), len(file_proto_proc_v1_proc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proc_v1_proc_proto_goTypes,
		DependencyIndexes: file_proto_proc_v1_proc_proto_depIdxs,
		MessageInfos:      file_proto_proc_v1_proc_proto_msgTypes,
	}.Build()
	File_proto_proc_v1_proc_proto = out.File
	file_proto_proc_v1_proc_proto_goTypes = nil
	file_proto_proc_v1_proc_proto_depIdxs = nil
}
