// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/proc/v1/proc.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcService_SpawnProc_FullMethodName = "/proc.v1.ProcService/SpawnProc"
	ProcService_SpawnLXC_FullMethodName  = "/proc.v1.ProcService/SpawnLXC"
)

// ProcServiceClient is the client API for ProcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcServiceClient interface {
	SpawnProc(ctx context.Context, in *SpawnProcRequest, opts ...grpc.CallOption) (*SpawnProcResponse, error)
	SpawnLXC(ctx context.Context, in *SpawnLXCRequest, opts ...grpc.CallOption) (*SpawnLXCResponse, error)
}

type procServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcServiceClient(cc grpc.ClientConnInterface) ProcServiceClient {
	return &procServiceClient{cc}
}

func (c *procServiceClient) SpawnProc(ctx context.Context, in *SpawnProcRequest, opts ...grpc.CallOption) (*SpawnProcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnProcResponse)
	err := c.cc.Invoke(ctx, ProcService_SpawnProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procServiceClient) SpawnLXC(ctx context.Context, in *SpawnLXCRequest, opts ...grpc.CallOption) (*SpawnLXCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnLXCResponse)
	err := c.cc.Invoke(ctx, ProcService_SpawnLXC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcServiceServer is the server API for ProcService service.
// All implementations must embed UnimplementedProcServiceServer
// for forward compatibility.
type ProcServiceServer interface {
	SpawnProc(context.Context, *SpawnProcRequest) (*SpawnProcResponse, error)
	SpawnLXC(context.Context, *SpawnLXCRequest) (*SpawnLXCResponse, error)
	mustEmbedUnimplementedProcServiceServer()
}

// UnimplementedProcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcServiceServer struct{}

func (UnimplementedProcServiceServer) SpawnProc(context.Context, *SpawnProcRequest) (*SpawnProcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpawnProc not implemented")
}
func (UnimplementedProcServiceServer) SpawnLXC(context.Context, *SpawnLXCRequest) (*SpawnLXCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpawnLXC not implemented")
}
func (UnimplementedProcServiceServer) mustEmbedUnimplementedProcServiceServer() {}
func (UnimplementedProcServiceServer) testEmbeddedByValue()                     {}

// UnsafeProcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcServiceServer will
// result in compilation errors.
type UnsafeProcServiceServer interface {
	mustEmbedUnimplementedProcServiceServer()
}

func RegisterProcServiceServer(s grpc.ServiceRegistrar, srv ProcServiceServer) {
	// If the following call panics, it indicates UnimplementedProcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcService_ServiceDesc, srv)
}

func _ProcService_SpawnProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnProcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcServiceServer).SpawnProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcService_SpawnProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcServiceServer).SpawnProc(ctx, req.(*SpawnProcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcService_SpawnLXC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnLXCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcServiceServer).SpawnLXC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcService_SpawnLXC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcServiceServer).SpawnLXC(ctx, req.(*SpawnLXCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcService_ServiceDesc is the grpc.ServiceDesc for ProcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proc.v1.ProcService",
	HandlerType: (*ProcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpawnProc",
			Handler:    _ProcService_SpawnProc_Handler,
		},
		{
			MethodName: "SpawnLXC",
			Handler:    _ProcService_SpawnLXC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proc/v1/proc.proto",
}
