// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/net/v1/net.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncQueueRequest) Reset() {
	*x = SyncQueueRequest{}
	mi := &file_proto_net_v1_net_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncQueueRequest) ProtoMessage() {}

func (x *SyncQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_net_v1_net_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncQueueRequest.ProtoReflect.Descriptor instead.
func (*SyncQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_net_v1_net_proto_rawDescGZIP(), []int{0}
}

func (x *SyncQueueRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type SyncQueueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemsSynced    int32                  `protobuf:"varint,1,opt,name=items_synced,json=itemsSynced,proto3" json:"items_synced,omitempty"`
	ItemsRemaining int32                  `protobuf:"varint,2,opt,name=items_remaining,json=itemsRemaining,proto3" json:"items_remaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncQueueResponse) Reset() {
	*x = SyncQueueResponse{}
	mi := &file_proto_net_v1_net_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncQueueResponse) ProtoMessage() {}

func (x *SyncQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_net_v1_net_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncQueueResponse.ProtoReflect.Descriptor instead.
func (*SyncQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_net_v1_net_proto_rawDescGZIP(), []int{1}
}

func (x *SyncQueueResponse) GetItemsSynced() int32 {
	if x != nil {
		return x.ItemsSynced
	}
	return 0
}

func (x *SyncQueueResponse) GetItemsRemaining() int32 {
	if x != nil {
		return x.ItemsRemaining
	}
	return 0
}

type APIGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetRequest) Reset() {
	*x = APIGetRequest{}
	mi := &file_proto_net_v1_net_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetRequest) ProtoMessage() {}

func (x *APIGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_net_v1_net_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetRequest.ProtoReflect.Descriptor instead.
func (*APIGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_net_v1_net_proto_rawDescGZIP(), []int{2}
}

func (x *APIGetRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *APIGetRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type APIGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetResponse) Reset() {
	*x = APIGetResponse{}
	mi := &file_proto_net_v1_net_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetResponse) ProtoMessage() {}

func (x *APIGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_net_v1_net_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetResponse.ProtoReflect.Descriptor instead.
func (*APIGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_net_v1_net_proto_rawDescGZIP(), []int{3}
}

func (x *APIGetResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APIGetResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_proto_net_v1_net_proto protoreflect.FileDescriptor

const file_proto_net_v1_net_proto_rawDesc = "" +
	"\n" +
	"\x16proto/net/v1/net.proto\x12\x06net.v1\"7\n" +
	"\x10SyncQueueRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"_\n" +
	"\x11SyncQueueResponse\x12!\n" +
	"\fitems_synced\x18\x01 \x01(\x05R\vitemsSynced\x12'\n" +
	"\x0fitems_remaining\x18\x02 \x01(\x05R\x0eitemsRemaining\"P\n" +
	"\rAPIGetRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"E\n" +
	"\x0eAPIGetResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body2\x87\x01\n" +
	"\n" +
	"NetService\x12@\n" +
	"\tSyncQueue\x12\x18.net.v1.SyncQueueRequest\x1a\x19.net.v1.SyncQueueResponse\x127\n" +
	"\x06APIGet\x12\x15.net.v1.APIGetRequest\x1a\x16.net.v1.APIGetResponseB*Z(github.com/j33pguy/33-linux/proto/net/v1b\x06proto3"

var (
	file_proto_net_v1_net_proto_rawDescOnce sync.Once
	file_proto_net_v1_net_proto_rawDescData []byte
)

func file_proto_net_v1_net_proto_rawDescGZIP() []byte {
	file_proto_net_v1_net_proto_rawDescOnce.Do(func() {
		file_proto_net_v1_net_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_net_v1_net_proto_rawDesc), len(file_proto_net_v1_net_proto_rawDesc)))
	})
	return file_proto_net_v1_net_proto_rawDescData
}

var file_proto_net_v1_net_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_net_v1_net_proto_goTypes = []any{
	(*SyncQueueRequest)(nil),  // 0: net.v1.SyncQueueRequest
	(*SyncQueueResponse)(nil), // 1: net.v1.SyncQueueResponse
	(*APIGetRequest)(nil),     // 2: net.v1.APIGetRequest
	(*APIGetResponse)(nil),    // 3: net.v1.APIGetResponse
}
var file_proto_net_v1_net_proto_depIdxs = []int32{
	0, // 0: net.v1.NetService.SyncQueue:input_type -> net.v1.SyncQueueRequest
	2, // 1: net.v1.NetService.APIGet:input_type -> net.v1.APIGetRequest
	1, // 2: net.v1.NetService.SyncQueue:output_type -> net.v1.SyncQueueResponse
	3, // 3: net.v1.NetService.APIGet:output_type -> net.v1.APIGetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_net_v1_net_proto_init() }
func file_proto_net_v1_net_proto_init() {
	if File_proto_net_v1_net_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_net_v1_net_proto_rawDesc), len(file_proto_net_v1_net_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_net_v1_net_proto_goTypes,
		DependencyIndexes: file_proto_net_v1_net_proto_depIdxs,
		MessageInfos:      file_proto_net_v1_net_proto_msgTypes,
	}.Build()
	File_proto_net_v1_net_proto = out.File
	file_proto_net_v1_net_proto_goTypes = nil
	file_proto_net_v1_net_proto_depIdxs = nil
}
