// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/net/v1/net.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetService_SyncQueue_FullMethodName = "/net.v1.NetService/SyncQueue"
	NetService_APIGet_FullMethodName    = "/net.v1.NetService/APIGet"
)

// NetServiceClient is the client API for NetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetServiceClient interface {
	SyncQueue(ctx context.Context, in *SyncQueueRequest, opts ...grpc.CallOption) (*SyncQueueResponse, error)
	APIGet(ctx context.Context, in *APIGetRequest, opts ...grpc.CallOption) (*APIGetResponse, error)
}

type netServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetServiceClient(cc grpc.ClientConnInterface) NetServiceClient {
	return &netServiceClient{cc}
}

func (c *netServiceClient) SyncQueue(ctx context.Context, in *SyncQueueRequest, opts ...grpc.CallOption) (*SyncQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncQueueResponse)
	err := c.cc.Invoke(ctx, NetService_SyncQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netServiceClient) APIGet(ctx context.Context, in *APIGetRequest, opts ...grpc.CallOption) (*APIGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIGetResponse)
	err := c.cc.Invoke(ctx, NetService_APIGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetServiceServer is the server API for NetService service.
// All implementations must embed UnimplementedNetServiceServer
// for forward compatibility.
type NetServiceServer interface {
	SyncQueue(context.Context, *SyncQueueRequest) (*SyncQueueResponse, error)
	APIGet(context.Context, *APIGetRequest) (*APIGetResponse, error)
	mustEmbedUnimplementedNetServiceServer()
}

// UnimplementedNetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetServiceServer struct{}

func (UnimplementedNetServiceServer) SyncQueue(context.Context, *SyncQueueRequest) (*SyncQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncQueue not implemented")
}
func (UnimplementedNetServiceServer) APIGet(context.Context, *APIGetRequest) (*APIGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method APIGet not implemented")
}
func (UnimplementedNetServiceServer) mustEmbedUnimplementedNetServiceServer() {}
func (UnimplementedNetServiceServer) testEmbeddedByValue()                    {}

// UnsafeNetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetServiceServer will
// result in compilation errors.
type UnsafeNetServiceServer interface {
	mustEmbedUnimplementedNetServiceServer()
}

func RegisterNetServiceServer(s grpc.ServiceRegistrar, srv NetServiceServer) {
	// If the following call panics, it indicates UnimplementedNetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetService_ServiceDesc, srv)
}

func _NetService_SyncQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetServiceServer).SyncQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetService_SyncQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetServiceServer).SyncQueue(ctx, req.(*SyncQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetService_APIGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetServiceServer).APIGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetService_APIGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetServiceServer).APIGet(ctx, req.(*APIGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetService_ServiceDesc is the grpc.ServiceDesc for NetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "net.v1.NetService",
	HandlerType: (*NetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncQueue",
			Handler:    _NetService_SyncQueue_Handler,
		},
		{
			MethodName: "APIGet",
			Handler:    _NetService_APIGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/net/v1/net.proto",
}
