// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/file/v1/file.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileRequest) Reset() {
	*x = StoreFileRequest{}
	mi := &file_proto_file_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileRequest) ProtoMessage() {}

func (x *StoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileRequest.ProtoReflect.Descriptor instead.
func (*StoreFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *StoreFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StoreFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoreFileRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type StoreFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	QueuedForSync bool                   `protobuf:"varint,2,opt,name=queued_for_sync,json=queuedForSync,proto3" json:"queued_for_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileResponse) Reset() {
	*x = StoreFileResponse{}
	mi := &file_proto_file_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileResponse) ProtoMessage() {}

func (x *StoreFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileResponse.ProtoReflect.Descriptor instead.
func (*StoreFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *StoreFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StoreFileResponse) GetQueuedForSync() bool {
	if x != nil {
		return x.QueuedForSync
	}
	return false
}

type LoadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadFileRequest) Reset() {
	*x = LoadFileRequest{}
	mi := &file_proto_file_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadFileRequest) ProtoMessage() {}

func (x *LoadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadFileRequest.ProtoReflect.Descriptor instead.
func (*LoadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *LoadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LoadFileRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type LoadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ModifiedAt    int64                  `protobuf:"varint,2,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadFileResponse) Reset() {
	*x = LoadFileResponse{}
	mi := &file_proto_file_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadFileResponse) ProtoMessage() {}

func (x *LoadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadFileResponse.ProtoReflect.Descriptor instead.
func (*LoadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *LoadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LoadFileResponse) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

var File_proto_file_v1_file_proto protoreflect.FileDescriptor

const file_proto_file_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x18proto/file/v1/file.proto\x12\afile.v1\"_\n" +
	"\x10StoreFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"T\n" +
	"\x11StoreFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12&\n" +
	"\x0fqueued_for_sync\x18\x02 \x01(\bR\rqueuedForSync\"J\n" +
	"\x0fLoadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"G\n" +
	"\x10LoadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vmodified_at\x18\x02 \x01(\x03R\n" +
	"modifiedAt2\x92\x01\n" +
	"\vFileService\x12B\n" +
	"\tStoreFile\x12\x19.file.v1.StoreFileRequest\x1a\x1a.file.v1.StoreFileResponse\x12?\n" +
	"\bLoadFile\x12\x18.file.v1.LoadFileRequest\x1a\x19.file.v1.LoadFileResponseB+Z)github.com/j33pguy/33-linux/proto/file/v1b\x06proto3"

var (
	file_proto_file_v1_file_proto_rawDescOnce sync.Once
	file_proto_file_v1_file_proto_rawDescData []byte
)

func file_proto_file_v1_file_proto_rawDescGZIP() []byte {
	file_proto_file_v1_file_proto_rawDescOnce.Do(func() {
		file_proto_file_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_v1_file_proto_rawDesc), len(file_proto_file_v1_file_proto_rawDesc)))
	})
	return file_proto_file_v1_file_proto_rawDescData
}

var file_proto_file_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_file_v1_file_proto_goTypes = []any{
	(*StoreFileRequest)(nil),  // 0: file.v1.StoreFileRequest
	(*StoreFileResponse)(nil), // 1: file.v1.StoreFileResponse
	(*LoadFileRequest)(nil),   // 2: file.v1.LoadFileRequest
	(*LoadFileResponse)(nil),  // 3: file.v1.LoadFileResponse
}
var file_proto_file_v1_file_proto_depIdxs = []int32{
	0, // 0: file.v1.FileService.StoreFile:input_type -> file.v1.StoreFileRequest
	2, // 1: file.v1.FileService.LoadFile:input_type -> file.v1.LoadFileRequest
	1, // 2: file.v1.FileService.StoreFile:output_type -> file.v1.StoreFileResponse
	3, // 3: file.v1.FileService.LoadFile:output_type -> file.v1.LoadFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_file_v1_file_proto_init() }
func file_proto_file_v1_file_proto_init() {
	if File_proto_file_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_v1_file_proto_rawDesc), len(file_proto_file_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_v1_file_proto_goTypes,
		DependencyIndexes: file_proto_file_v1_file_proto_depIdxs,
		MessageInfos:      file_proto_file_v1_file_proto_msgTypes,
	}.Build()
	File_proto_file_v1_file_proto = out.File
	file_proto_file_v1_file_proto_goTypes = nil
	file_proto_file_v1_file_proto_depIdxs = nil
}
