// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/hw/v1/hw.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectDevicesRequest) Reset() {
	*x = DetectDevicesRequest{}
	mi := &file_proto_hw_v1_hw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectDevicesRequest) ProtoMessage() {}

func (x *DetectDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hw_v1_hw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectDevicesRequest.ProtoReflect.Descriptor instead.
func (*DetectDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hw_v1_hw_proto_rawDescGZIP(), []int{0}
}

func (x *DetectDevicesRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_hw_v1_hw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hw_v1_hw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_hw_v1_hw_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DetectDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectDevicesResponse) Reset() {
	*x = DetectDevicesResponse{}
	mi := &file_proto_hw_v1_hw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectDevicesResponse) ProtoMessage() {}

func (x *DetectDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hw_v1_hw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectDevicesResponse.ProtoReflect.Descriptor instead.
func (*DetectDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_hw_v1_hw_proto_rawDescGZIP(), []int{2}
}

func (x *DetectDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AuthDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthDeviceRequest) Reset() {
	*x = AuthDeviceRequest{}
	mi := &file_proto_hw_v1_hw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthDeviceRequest) ProtoMessage() {}

func (x *AuthDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hw_v1_hw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthDeviceRequest.ProtoReflect.Descriptor instead.
func (*AuthDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_hw_v1_hw_proto_rawDescGZIP(), []int{3}
}

func (x *AuthDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthDeviceRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type AuthDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthDeviceResponse) Reset() {
	*x = AuthDeviceResponse{}
	mi := &file_proto_hw_v1_hw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthDeviceResponse) ProtoMessage() {}

func (x *AuthDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hw_v1_hw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthDeviceResponse.ProtoReflect.Descriptor instead.
func (*AuthDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_hw_v1_hw_proto_rawDescGZIP(), []int{4}
}

func (x *AuthDeviceResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *AuthDeviceResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_proto_hw_v1_hw_proto protoreflect.FileDescriptor

const file_proto_hw_v1_hw_proto_rawDesc = "" +
	"\n" +
	"\x14proto/hw/v1/hw.proto\x12\x05hw.v1\";\n" +
	"\x14DetectDevicesRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"T\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"@\n" +
	"\x15DetectDevicesResponse\x12'\n" +
	"\adevices\x18\x01 \x03(\v2\r.hw.v1.DeviceR\adevices\"U\n" +
	"\x11AuthDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"W\n" +
	"\x12AuthDeviceResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId2\xa1\x01\n" +
	"\x10HWSpawnerService\x12J\n" +
	"\rDetectDevices\x12\x1b.hw.v1.DetectDevicesRequest\x1a\x1c.hw.v1.DetectDevicesResponse\x12A\n" +
	"\n" +
	"AuthDevice\x12\x18.hw.v1.AuthDeviceRequest\x1a\x19.hw.v1.AuthDeviceResponseB)Z'github.com/j33pguy/33-linux/proto/hw/v1b\x06proto3"

var (
	file_proto_hw_v1_hw_proto_rawDescOnce sync.Once
	file_proto_hw_v1_hw_proto_rawDescData []byte
)

func file_proto_hw_v1_hw_proto_rawDescGZIP() []byte {
	file_proto_hw_v1_hw_proto_rawDescOnce.Do(func() {
		file_proto_hw_v1_hw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hw_v1_hw_proto_rawDesc), len(file_proto_hw_v1_hw_proto_rawDesc)))
	})
	return file_proto_hw_v1_hw_proto_rawDescData
}

var file_proto_hw_v1_hw_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_hw_v1_hw_proto_goTypes = []any{
	(*DetectDevicesRequest)(nil),  // 0: hw.v1.DetectDevicesRequest
	(*Device)(nil),                // 1: hw.v1.Device
	(*DetectDevicesResponse)(nil), // 2: hw.v1.DetectDevicesResponse
	(*AuthDeviceRequest)(nil),     // 3: hw.v1.AuthDeviceRequest
	(*AuthDeviceResponse)(nil),    // 4: hw.v1.AuthDeviceResponse
}
var file_proto_hw_v1_hw_proto_depIdxs = []int32{
	1, // 0: hw.v1.DetectDevicesResponse.devices:type_name -> hw.v1.Device
	0, // 1: hw.v1.HWSpawnerService.DetectDevices:input_type -> hw.v1.DetectDevicesRequest
	3, // 2: hw.v1.HWSpawnerService.AuthDevice:input_type -> hw.v1.AuthDeviceRequest
	2, // 3: hw.v1.HWSpawnerService.DetectDevices:output_type -> hw.v1.DetectDevicesResponse
	4, // 4: hw.v1.HWSpawnerService.AuthDevice:output_type -> hw.v1.AuthDeviceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hw_v1_hw_proto_init() }
func file_proto_hw_v1_hw_proto_init() {
	if File_proto_hw_v1_hw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hw_v1_hw_proto_rawDesc), len(file_proto_hw_v1_hw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hw_v1_hw_proto_goTypes,
		DependencyIndexes: file_proto_hw_v1_hw_proto_depIdxs,
		MessageInfos:      file_proto_hw_v1_hw_proto_msgTypes,
	}.Build()
	File_proto_hw_v1_hw_proto = out.File
	file_proto_hw_v1_hw_proto_goTypes = nil
	file_proto_hw_v1_hw_proto_depIdxs = nil
}
