// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/hw/v1/hw.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HWSpawnerService_DetectDevices_FullMethodName = "/hw.v1.HWSpawnerService/DetectDevices"
	HWSpawnerService_AuthDevice_FullMethodName    = "/hw.v1.HWSpawnerService/AuthDevice"
)

// HWSpawnerServiceClient is the client API for HWSpawnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HWSpawnerServiceClient interface {
	DetectDevices(ctx context.Context, in *DetectDevicesRequest, opts ...grpc.CallOption) (*DetectDevicesResponse, error)
	AuthDevice(ctx context.Context, in *AuthDeviceRequest, opts ...grpc.CallOption) (*AuthDeviceResponse, error)
}

type hWSpawnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHWSpawnerServiceClient(cc grpc.ClientConnInterface) HWSpawnerServiceClient {
	return &hWSpawnerServiceClient{cc}
}

func (c *hWSpawnerServiceClient) DetectDevices(ctx context.Context, in *DetectDevicesRequest, opts ...grpc.CallOption) (*DetectDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectDevicesResponse)
	err := c.cc.Invoke(ctx, HWSpawnerService_DetectDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hWSpawnerServiceClient) AuthDevice(ctx context.Context, in *AuthDeviceRequest, opts ...grpc.CallOption) (*AuthDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthDeviceResponse)
	err := c.cc.Invoke(ctx, HWSpawnerService_AuthDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HWSpawnerServiceServer is the server API for HWSpawnerService service.
// All implementations must embed UnimplementedHWSpawnerServiceServer
// for forward compatibility.
type HWSpawnerServiceServer interface {
	DetectDevices(context.Context, *DetectDevicesRequest) (*DetectDevicesResponse, error)
	AuthDevice(context.Context, *AuthDeviceRequest) (*AuthDeviceResponse, error)
	mustEmbedUnimplementedHWSpawnerServiceServer()
}

// UnimplementedHWSpawnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHWSpawnerServiceServer struct{}

func (UnimplementedHWSpawnerServiceServer) DetectDevices(context.Context, *DetectDevicesRequest) (*DetectDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectDevices not implemented")
}
func (UnimplementedHWSpawnerServiceServer) AuthDevice(context.Context, *AuthDeviceRequest) (*AuthDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthDevice not implemented")
}
func (UnimplementedHWSpawnerServiceServer) mustEmbedUnimplementedHWSpawnerServiceServer() {}
func (UnimplementedHWSpawnerServiceServer) testEmbeddedByValue()                          {}

// UnsafeHWSpawnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HWSpawnerServiceServer will
// result in compilation errors.
type UnsafeHWSpawnerServiceServer interface {
	mustEmbedUnimplementedHWSpawnerServiceServer()
}

func RegisterHWSpawnerServiceServer(s grpc.ServiceRegistrar, srv HWSpawnerServiceServer) {
	// If the following call panics, it indicates UnimplementedHWSpawnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HWSpawnerService_ServiceDesc, srv)
}

func _HWSpawnerService_DetectDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HWSpawnerServiceServer).DetectDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HWSpawnerService_DetectDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HWSpawnerServiceServer).DetectDevices(ctx, req.(*DetectDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HWSpawnerService_AuthDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HWSpawnerServiceServer).AuthDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HWSpawnerService_AuthDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HWSpawnerServiceServer).AuthDevice(ctx, req.(*AuthDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HWSpawnerService_ServiceDesc is the grpc.ServiceDesc for HWSpawnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HWSpawnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hw.v1.HWSpawnerService",
	HandlerType: (*HWSpawnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectDevices",
			Handler:    _HWSpawnerService_DetectDevices_Handler,
		},
		{
			MethodName: "AuthDevice",
			Handler:    _HWSpawnerService_AuthDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hw/v1/hw.proto",
}
